### ISSUE TITLE
[Caddy] chown webroot files occurring twice

### ISSUE THREAD

**Issue by adamgoose** [dockhippie/php-cli#6]
In the Caddy base image, the webroot files are being chowned https://github.com/dockhippie/caddy/blob/master/rootfs/etc/s6/caddy/setup#L13-L14. Its also happening in the PHP image https://github.com/dockhippie/php/blob/master/caddy/rootfs/etc/s6/php/setup#L45-L46.

It takes FOREVER! I'm looking into ways to speed it up.

**Comment by adamgoose** [comment]
By "FOREVER", I mean roughly 6 minutes for a standard Laravel app with composer deps already installed (we aren't using your runtime `composer install` feature, rather doing it during CI).

**Comment by tboerger** [comment]
This is already the fastest option to chown the files properly. You can speed it up if you chown the files within your Dockerfile before runtime

**Comment by adamgoose** [comment]
Will something like this work?

```Dockerfile
USER caddy
ADD . /srv/www
RUN composer install
USER root
```

**Comment by tboerger** [comment]
Maybe, that's something I have not tried. I have always chowned after ADD

**Comment by adamgoose** [comment]
Ok, so new plan.

```Dockerfile
ADD composer.json composer.lock /srv/www
RUN su-exec caddy composer install--no-interaction --no-dev --prefer-dist --no-scripts --no-autoloader
ADD . /srv/www
RUN chown -R caddy:caddy /srv/www
RUN su-exec caddy composer install --no-interaction --no-dev --prefer-dist
```

**Comment by tboerger** [comment]
Not the most beautiful solution but it should work.

**Comment by tboerger** [comment]
The php-caddy image is not using this image anymore.
